-- +goose Up
CREATE TABLE paas_client (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_key        varchar(64)  NOT NULL,
    app_secret     varchar(128) NOT NULL DEFAULT '',
    secret_hashed  smallint     NOT NULL DEFAULT 0,
    site_code      varchar(32)  NOT NULL DEFAULT '',
    status         smallint     NOT NULL DEFAULT 1,
    remark         varchar(255) NOT NULL DEFAULT '',
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uk_ad_paas_client_app_key ON paas_client (app_key);
COMMENT ON TABLE paas_client IS '开放API调用方凭证镜像';

-- +goose Down
DROP TABLE IF EXISTS paas_client;
