-- +goose Up

-- 广告位模板
CREATE TABLE ad_slot (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(64)  NOT NULL,
    name        varchar(128) NOT NULL DEFAULT '',
    slot_type   varchar(32)  NOT NULL DEFAULT 'banner', -- banner/splash/feed/player
    width       int          NOT NULL DEFAULT 0,
    height      int          NOT NULL DEFAULT 0,
    status      smallint     NOT NULL DEFAULT 1, -- 1启用 0停用
    remark      varchar(255) NOT NULL DEFAULT '',
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_ad_slot_code ON ad_slot (code);

-- 素材
CREATE TABLE ad_creative (
    id                varchar(16)  PRIMARY KEY,
    title             varchar(128) NOT NULL DEFAULT '',
    media_url         varchar(512) NOT NULL DEFAULT '',
    link_url          varchar(512) NOT NULL DEFAULT '',
    storage_object_id varchar(32)  NOT NULL DEFAULT '',
    status            smallint     NOT NULL DEFAULT 1, -- 1就绪 0下架
    remark            varchar(255) NOT NULL DEFAULT '',
    created_at        timestamptz  NOT NULL DEFAULT now(),
    updated_at        timestamptz  NOT NULL DEFAULT now()
);

-- 投放
CREATE TABLE ad_campaign (
    id          varchar(16)  PRIMARY KEY,
    name        varchar(128) NOT NULL DEFAULT '',
    slot_id     bigint       NOT NULL,
    creative_id varchar(16)  NOT NULL,
    site_code   varchar(32)  NOT NULL DEFAULT '', -- 空=全站；非空=指定站
    priority    int          NOT NULL DEFAULT 100,
    weight      int          NOT NULL DEFAULT 100,
    status      smallint     NOT NULL DEFAULT 1, -- 1投放中 0暂停
    start_at    timestamptz,
    end_at      timestamptz,
    remark      varchar(255) NOT NULL DEFAULT '',
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_ad_campaign_slot ON ad_campaign (slot_id, status);
CREATE INDEX idx_ad_campaign_site ON ad_campaign (site_code, status);
CREATE INDEX idx_ad_campaign_creative ON ad_campaign (creative_id);

-- 简易事件上报（曝光/点击）
CREATE TABLE ad_event (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type  varchar(16)  NOT NULL, -- impression/click
    campaign_id varchar(16)  NOT NULL DEFAULT '',
    creative_id varchar(16)  NOT NULL DEFAULT '',
    slot_code   varchar(64)  NOT NULL DEFAULT '',
    site_code   varchar(32)  NOT NULL DEFAULT '',
    app_key     varchar(64)  NOT NULL DEFAULT '',
    created_at  timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_ad_event_created ON ad_event (created_at DESC);

-- +goose Down
DROP TABLE IF EXISTS ad_event;
DROP TABLE IF EXISTS ad_campaign;
DROP TABLE IF EXISTS ad_creative;
DROP TABLE IF EXISTS ad_slot;
